# Change these first
owner: Comparacar # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: /assinar
    url: https://www.comparacar.com.br/assinar
  - name: /assinar/carro
    url: https://www.comparacar.com.br/assinar/carro
  - name: /comprar/carro
    url: https://www.comparacar.com.br/comprar/carro

status-website:
  baseUrl: /uptime
  logoUrl: https://www.comparacar.com.br/static/favicon-white.png
  name: Comparacar Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
